import enum

class Module(enum.Enum):
    ACCOUNTS = "Accounts"
    CALLS = "Calls"
    CAMPAIGNS = "Campaigns"
    CASES = "Cases"
    CONTACTS = "Contacts"
    AOS_CONTRACTS = "AOS_Contracts"
    DOCUMENTS = "Documents"
    EMAILTEMPLATES = "EmailTemplates"
    EMAILS = "Emails"
    FP_EVENTS = "FP_events"
    AOS_INVOICES = "AOS_Invoices"
    AOK_KNOWLEDGE_BASE_CATEGORIES = "AOK_Knowledge_Base_Categories"
    AOK_KNOWLEDGEBASE = "AOK_KnowledgeBase"
    LEADS = "Leads"
    FP_EVENT_LOCATIONS = "FP_Event_Locations"
    JJWG_MAPS = "jjwg_Maps"
    JJWG_ADDRESS_CACHE = "jjwg_Address_Cache"
    JJWG_AREAS = "jjwg_Areas"
    JJWG_MARKERS = "jjwg_Markers"
    MEETINGS = "Meetings"
    NOTES = "Notes"
    OPPORTUNITIES = "Opportunities"
    AOS_PDF_TEMPLATES = "AOS_PDF_Templates"
    AOS_PRODUCTS = "AOS_Products"
    AOS_PRODUCT_CATEGORIES = "AOS_Product_Categories"
    PROJECT = "Project"
    AM_PROJECTTEMPLATES = "AM_ProjectTemplates"
    AOS_QUOTES = "AOS_Quotes"
    AOR_REPORTS = "AOR_Reports"
    SPOTS = "Spots"
    SURVEYS = "Surveys"
    TASKS = "Tasks"
    AOW_WORKFLOW = "AOW_WorkFlow"